language:
  - generic
sudo: required
services:
  - docker

before_install:
  - docker build -t miguelmaldonado/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true miguelmaldonado/docker-react-tutorial npm run test -- --coverage
